# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class DataPaletteService(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login',
            service_ver='release'):
        if url is None:
            url = 'https://kbase.us/services/service_wizard'
        self._service_ver = service_ver
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc,
            lookup_url=True)

    def list_data(self, params, context=None):
        """
        :param params: instance of type "ListDataParams" (todo: pagination?)
           -> structure: parameter "workspaces" of list of type
           "ws_name_or_id"
        :returns: instance of type "DataList" -> structure: parameter "data"
           of list of type "DataInfo" -> structure: parameter "ref" of type
           "ws_ref" (@id ws), parameter "meta" of String, parameter "src_nar"
           of String
        """
        return self._client.call_method(
            'DataPaletteService.list_data',
            [params], self._service_ver, context)

    def add_to_palette(self, params, context=None):
        """
        :param params: instance of type "AddToPaletteParams" -> structure:
           parameter "workspace" of type "ws_name_or_id", parameter
           "new_refs" of list of type "ObjectReference" (todo: allow passing
           in a reference chain) -> structure: parameter "ref" of type
           "ws_ref" (@id ws)
        """
        return self._client.call_method(
            'DataPaletteService.add_to_palette',
            [params], self._service_ver, context)

    def remove_from_palette(self, params, context=None):
        """
        :param params: instance of type "RemoveFromPaletteParams" ->
           structure: parameter "workspace" of type "ws_name_or_id",
           parameter "refs" of list of type "ws_ref" (@id ws)
        """
        return self._client.call_method(
            'DataPaletteService.remove_from_palette',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('DataPaletteService.status',
                                        [], self._service_ver, context)
