# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class DataPaletteService(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login',
            service_ver='release'):
        if url is None:
            url = 'https://kbase.us/services/service_wizard'
        self._service_ver = service_ver
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc,
            lookup_url=True)

    def list_data(self, params, context=None):
        """
        :param params: instance of type "ListDataParams" (todo: pagination?)
           -> structure: parameter "workspaces" of list of type
           "ws_name_or_id"
        :returns: instance of type "DataList" -> structure: parameter "data"
           of list of type "DataInfo" -> structure: parameter "ref" of type
           "ws_ref" (@id ws), parameter "info" of type "object_info"
           (Information about an object, including user provided metadata.
           obj_id objid - the numerical id of the object. obj_name name - the
           name of the object. type_string type - the type of the object.
           timestamp save_date - the save date of the object. obj_ver ver -
           the version of the object. username saved_by - the user that saved
           or copied the object. ws_id wsid - the workspace containing the
           object. ws_name workspace - the workspace containing the object.
           string chsum - the md5 checksum of the object. int size - the size
           of the object in bytes. usermeta meta - arbitrary user-supplied
           metadata about the object.) -> tuple of size 11: parameter "objid"
           of type "obj_id" (The unique, permanent numerical ID of an
           object.), parameter "name" of type "obj_name" (A string used as a
           name for an object. Any string consisting of alphanumeric
           characters and the characters |._- that is not an integer is
           acceptable.), parameter "type" of type "type_string" (A type
           string. Specifies the type and its version in a single string in
           the format [module].[typename]-[major].[minor]: module - a string.
           The module name of the typespec containing the type. typename - a
           string. The name of the type as assigned by the typedef statement.
           major - an integer. The major version of the type. A change in the
           major version implies the type has changed in a non-backwards
           compatible way. minor - an integer. The minor version of the type.
           A change in the minor version implies that the type has changed in
           a way that is backwards compatible with previous type definitions.
           In many cases, the major and minor versions are optional, and if
           not provided the most recent version will be used. Example:
           MyModule.MyType-3.1), parameter "save_date" of type "timestamp" (A
           time in the format YYYY-MM-DDThh:mm:ssZ, where Z is either the
           character Z (representing the UTC timezone) or the difference in
           time to UTC in the format +/-HHMM, eg: 2012-12-17T23:24:06-0500
           (EST time) 2013-04-03T08:56:32+0000 (UTC time)
           2013-04-03T08:56:32Z (UTC time)), parameter "version" of Long,
           parameter "saved_by" of type "username" (Login name of a KBase
           user account.), parameter "wsid" of type "ws_id" (The unique,
           permanent numerical ID of a workspace.), parameter "workspace" of
           type "ws_name" (A string used as a name for a workspace. Any
           string consisting of alphanumeric characters and "_", ".", or "-"
           that is not an integer is acceptable. The name may optionally be
           prefixed with the workspace owner's user name and a colon, e.g.
           kbasetest:my_workspace.), parameter "chsum" of String, parameter
           "size" of Long, parameter "meta" of type "usermeta" (User provided
           metadata about an object. Arbitrary key-value pairs provided by
           the user.) -> mapping from String to String
        """
        return self._client.call_method(
            'DataPaletteService.list_data',
            [params], self._service_ver, context)

    def add_to_palette(self, params, context=None):
        """
        :param params: instance of type "AddToPaletteParams" -> structure:
           parameter "workspace" of type "ws_name_or_id", parameter
           "new_refs" of list of type "ObjectReference" (todo: allow passing
           in a reference chain) -> structure: parameter "ref" of type
           "ws_ref" (@id ws)
        """
        return self._client.call_method(
            'DataPaletteService.add_to_palette',
            [params], self._service_ver, context)

    def remove_from_palette(self, params, context=None):
        """
        :param params: instance of type "RemoveFromPaletteParams" ->
           structure: parameter "workspace" of type "ws_name_or_id",
           parameter "refs" of list of type "ws_ref" (@id ws)
        """
        return self._client.call_method(
            'DataPaletteService.remove_from_palette',
            [params], self._service_ver, context)

    def copy_palette(self, params, context=None):
        """
        :param params: instance of type "CopyPaletteParams" -> structure:
           parameter "from_workspace" of type "ws_name_or_id", parameter
           "to_workspace" of type "ws_name_or_id"
        """
        return self._client.call_method(
            'DataPaletteService.copy_palette',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('DataPaletteService.status',
                                        [], self._service_ver, context)
